Fix playground not loading by adding  encoding="utf-8"
Since the js file in /playground/dist/assets might contain non-ASCII code, it is safer to specify the encoding when opening the file.

[issue on windoes] Otherwise, it might run into this error, which stops the playground from loading.


UnicodeDecodeError: 'charmap' codec can't decode byte 0x81 in position 163499: character maps to <undefined>


[This error happened on a Windows Machine]